import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from 'react';
import Search from './content/search'
import Pagenav from './content/paginav'
// import Dropdown1 from './content/dropdown';


const Home: NextPage = () => {
  return (

    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <div className={styles.topbar}>
      </div>

      <div className={styles.sidebar}>
        <img alt="" src="image3.png" className={styles.headpic} />
      </div>

      <main className={styles.main}>
        <div className={styles.header}>
          <div className={styles.headtext}>Place List</div>
          {/* <Dropdown1/> */}
          <div >
            <select defaultValue="Select Category" placeholder='Select Category' className={styles.dropdownhead}>
              <option id="hidden" disabled hidden>Select Category</option>
              <option value="Restaurent">Restaurent</option>
              <option value="Cafe">Cafe</option>
              <option value="Bakery">Bakery</option>
              <option value="All">All</option>
            </select>
          </div>
        </div>
        <div className={styles.content}>

          <Search />

        </div>
        <Pagenav />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
